### ISSUE TITLE
Misplaced Khudawadi marks on U+25CC DOTTED CIRCLE

### ISSUE THREAD

**Issue by dscorbett** [notofonts/khudawadi#1]
### Font
NotoSansKhudawadi-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/de091053cdfefbcaff5c0a968165a93a5e78df52/phaseIII_only/unhinted/ttf/NotoSansKhudawadi/NotoSansKhudawadi-Regular.ttf
Date: 2019-10-29

### Font version
Version 2.000

### Issue
Marks are not positioned correctly on U+25CC DOTTED CIRCLE.

### Character data
◌𑋟◌𑋣◌𑋤◌𑋩◌𑋪
U+25CC DOTTED CIRCLE
U+112DF KHUDAWADI SIGN ANUSVARA
U+25CC DOTTED CIRCLE
U+112E3 KHUDAWADI VOWEL SIGN U
U+25CC DOTTED CIRCLE
U+112E4 KHUDAWADI VOWEL SIGN UU
U+25CC DOTTED CIRCLE
U+112E9 KHUDAWADI SIGN NUKTA
U+25CC DOTTED CIRCLE
U+112EA KHUDAWADI SIGN VIRAMA

### Screenshot
![◌𑋟◌𑋣◌𑋤◌𑋩◌𑋪](https://user-images.githubusercontent.com/1124347/67792879-472d7580-fa50-11e9-9b38-28571d2ac305.png)

**Comment by simoncozens** [comment]
This should be fixed in 6ddd3f3.
