### ISSUE TITLE
Could you dub anchoring of virama etc with default anchoring?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/khudawadi#4]
### Title
Please dub anchoring of virama (and other top/bottom umlauts) with default anchoring.

### Font 
NotoSansKhudawadi-Regular.ttf

### Where the font came from, and when
Site: notofonts.github.io distribution hub
Date: 2022-10-30

### Font Version
2.003

### OS name and version
W10 21H1

### Application name and version
Qt 6.1.3

### Issue
  1. Write something unrelated (maybe in another font), then 25CC+virama
  2. Virama is misplaced.
  3. Virama should be at least somewhere in place.

As dotted circle is not a high-priority thing, I’m not asking for left-side umlauts like I, and not for complete fix. Just gag somehow to make it hang somewhere near.

### Character data
25CC Dotted circle
112EA Khudawadi sign Virama
(possibly other umlauts)

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/198897263-d65552cc-4316-4c9e-ab9d-8eca8bd72416.png)

### My fixes into older font
1. Moved virama to the left.
![image](https://user-images.githubusercontent.com/10164882/198897618-f6cc2f42-96c2-45e6-ae9d-3e9b10f42511.png)
2. RLIG dotted circle + virama
![image](https://user-images.githubusercontent.com/10164882/198897712-4930070c-d1f4-4832-894a-89e771041a37.png)
In some fonts like Siddham the 2nd DOES BREAK things so IDK whether it’s safe. So I’m asking just for 1.

**Comment by simoncozens** [comment]
Looks OK these days:

![shape](https://user-images.githubusercontent.com/106728/210358624-b4052215-03be-4f93-b52b-c24dfbd1ef5c.png)

**Comment by Mercury13** [comment]
Looks badly in specific software under mixture of fonts :(

**Comment by Mercury13** [comment]
Let it be, probably managed to circumvent
